export const generateEmailTemplate = (formData) => {
  return `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 5px;">
        <h2 style="color: #002a50;">New Contact Form Submission</h2>
        <p>Hi there,</p>
        <p>You have received a new message from your contact form. Below are the details:</p>
  
        <div style="background-color: #f9f9f9; padding: 15px; border-radius: 5px;">
          <p><strong>Name:</strong> ${formData.firstName} ${
    formData.lastName
  }</p>
          <p><strong>Email:</strong> <a href="mailto:${
            formData.email
          }" style="color: #002a50;">${formData.email}</a></p>
          <p><strong>Phone:</strong> ${
            formData.phone ? formData.phone : "N/A"
          }</p>
          <p><strong>Subject:</strong> ${
            formData.subject ? formData.subject : "N/A"
          }</p>
          <p><strong>Message:</strong></p>
          <p style="border-left: 4px solid #002a50; padding-left: 10px;">${
            formData.message
          }</p>
        </div>
  
        <p>If you need to reply, you can respond directly to <a href="mailto:${
          formData.email
        }" style="color: #002a50;">${formData.email}</a>.</p>
        
        <hr>
        <p style="color: #999; font-size: 12px;">This email was generated by the SurfacePix Contact Form.</p>
      </div>
    `;
};
